---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
library(gert)
```

# bangkok-gtfs

<!-- badges: start -->
<!-- badges: end -->

The goal of bangkok-gtfs is to make daily snapshots of Bangkok GTFS accessible to anyone. 
This project started on 26/04/2022. 
Better late than never!

The table below is updated every time there is a new snapshot of GTFS.

```{r, echo = FALSE}
gert::git_log(max = 10000000L) %>%
  filter(time == min(time) | grepl("^GTFS snapshot\\n$", message)) %>%
  filter(commit != "a1b9d2d20ca60965b61d530d1e187651c84dff1a") %>% # stuffed up
  mutate(download_link = paste0("https://github.com/asiripanich/bangkok-gtfs/tree/", commit, "/data/gtfs")) %>%
  select(time, download_link) %>%
  arrange(-order(time)) %>%
  knitr::kable()
```

All commits:

```{r, echo = FALSE}
gert::git_log(max = 10000000L) %>%
  knitr::kable()
```
